services:
  app:
    container_name: app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - mail-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mail-network

  mail:
    build:
      context: mail
    container_name: mail
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge