services:
  app:
    container_name: app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mail:
    build:
      context: mail
    container_name: mail-server
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"